### ISSUE TITLE
Dark theme background color

### ISSUE THREAD

**Issue by wiryadev** [catalinghita8/android-compose-mvvm-foodies#5]
There is a small issue with background color in dark theme becaus of usage of the same color for background both in dark and light pallete. See below image:

Home             |  Detail
:-------------------------:|:-------------------------:
![Screenshot_1625833685](https://user-images.githubusercontent.com/26060382/125079518-ed6ac300-e0ed-11eb-8ec7-ea964a8c71ee.png) | ![Screenshot_1625833691](https://user-images.githubusercontent.com/26060382/125079527-f196e080-e0ed-11eb-8623-6228c9bb0dfc.png)

I changed the background color for dark pallete so it looks like this
Home             |  Detail
:-------------------------:|:-------------------------:
![Screenshot_1625833801](https://user-images.githubusercontent.com/26060382/125079787-36227c00-e0ee-11eb-94f0-4305072455d9.png) | ![Screenshot_1625833822](https://user-images.githubusercontent.com/26060382/125079776-33c02200-e0ee-11eb-8a07-019de31fa26d.png)

Are you fine with this? If so i will open new request.

**Comment by catalinghita8** [comment]
It looks fine. I have overlooked the dark theming, thanks.

Please open a PR and I will have a look into the code as well.

**Comment by wiryadev** [comment]
> It looks fine. I have overlooked the dark theming, thanks.
> 
> Please open a PR and I will have a look into the code as well.

no problem, thanks for this great learning resource. 
I opened it [here](https://github.com/catalinghita8/android-compose-mvvm-foodies/pull/6)
