### ISSUE TITLE
[Question] - Reducer

### ISSUE THREAD

**Issue by GuilhE** [catalinghita8/android-compose-mvvm-foodies#7]
https://github.com/catalinghita8/android-compose-mvvm-foodies/blob/888f46af1015f771a290937d31cc5ec26fe340de/app/src/main/java/com/codingtroops/composesample/base/BaseComponents.kt#L48

Aren't you sending the previous state? 🤔 
I can make it work if I use:
```
    override fun setState(state: () -> ViewState) {
        _viewState.value = state.invoke()
    }
```
or just `_viewState.value = state`. Maybe I'm missing the point 😅

**Comment by catalinghita8** [comment]
We are setting the previous state but only after we "reduce" it via the `reducer` extension function. 

We basically pass a reducer extension function called `reducer` that is applied to the old state i.e. `viewState.value`. After the old state has been updated via the reducer extension function, it is assigned to our `_viewState`.

Your approaches are also valid but the one I have used is more suggestive in regards to the redux pattern which defines that a state is reduced (updated) based on the previous state.
